require: rubocop-rspec

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - app/assets/images/**/*
    - app/assets/javascripts/**/*
    - app/view/pages/*
    - bin/*
    - Rakefile
    - config/**/*
    - notepad/**/*
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - test/**/*
    - db/**/*
    - deploy/*.rb
    - deploy.rb
    - app/helpers/bootstrap_flash_helper.rb
    - app/helpers/bootstrap_deprecated_helper.rb
    - app/services/stat/reporting/general.rb
    - .git-hooks/**/*
    - files/**/*

Lint/UnneededDisable:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - app/views/**/*

Metrics/BlockLength:
  Exclude:
    - app/views/**/*
    - Guardfile
    - lib/tasks/auto_annotate_models.rake

Style/BracesAroundHashParameters:
  Exclude:
    - app/views/**/*

OutputSafety:
  Enabled: false

RSpec/FilePath:
  Enabled: false
  CustomTransform:
    RuboCop: rubocop
    RSpec: rspec

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
  ConsistentQuotesInMultiline: true

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleWording:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

TrailingCommaInLiteral:
  Enabled: false

TrailingCommaInArguments:
  Enabled: false

Documentation:
  Enabled: false

AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
