inherit_from: ../.rubocop.yml

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.4

RSpec/ExampleLength:
  Enabled: true
  Max: 20

RSpec/NestedGroups:
  Max: 4

RSpec/ImplicitExpect:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
